### PR TITLE
Added a Dockerfile to automate truffle migration

### PR DESCRIPTION
**Pull request by TheOriginalAlex**
Compiled truffle, but we'll run the migrate in a swarm or network where we actually wanna migrate.  We'll setup the command in a docker-compose or we'll set the command when we run `docker run`.

### CODE REVIEW

**Comment by anoff** [comment]
Why exactly do you not run `migrate`? In the initial setup everything will be local and most likely just a `docker-compose` or 3-4 individual `docker run` commands to spawn the whole system.
Wouldn't it be possible to bake the `truffle migrate` into the image itself?

**Comment by ghost** [comment]
Because you might wanna pass in `--network development`.  But, I guess I could make `truffle migrate` an entrypoint.

**Comment by kevinahuber** [comment]
I'll defer to @anoff on this one for review

**Comment by anoff** [comment]
Discussed a bit about this one with @TheOriginalAlex on slack yesterday. I think it would really benefit if we can have a reproducible docker image of `Sonar` that ships with the contract deployed. That would enable us to _hardcode_ the contract address for the **hydrogen** milestone making initial setup easier.

@TheOriginalAlex what's your take on this? Should we merge this PR as a first step and start another one? Code-wise this PR LGTM

**Comment by ghost** [comment]
@anoff: I will come back and address that.

**Comment by iamtrask** [comment]
given that we have a followup issue for the desired improvements. I'll go ahead and merge this guy. Great work @TheOriginalAlex !!

**Pull request merged**
