### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by jeamick**
Little change to make to smart-contracts more clear

### CODE REVIEW

**Comment by axelhodler** [comment]
Having these comments by itself to structure the code is not helpful I believe. Just a matter of time someone adds a modifier between the public functions or makes one of the public functions private.

If our goal is to make it super easy for a datascientist to grasp what the code does we should probably elaborate what a `modifier` or a `public function` is supposed to be.

**Comment by iamtrask** [comment]
I'm a big supporter of more comments / descriptions in this repo... @jeamick perhaps you'd be willing to elaborate in a bit more detail in your commenting?

**Comment by jeamick** [comment]
sorry, @axelhodler  I wanted to make more changes in order to update the documentation of the functions just to be more clear about the code.

**Comment by axelhodler** [comment]
sorry @jeamick for the late answer. Feel free to improve any docs around here. The conflicts should be resolved though.

Aside from the above, can you think of a good way we could enforce the truth of the comments? Such as that no one would add non-modifiers under the /** Modifiers */ comment?

**Comment by jeamick** [comment]
huh ? I didn't get really well what you were saying ...

**Pull request closed without merging**
