### PR TITLE
Update Readme with Ethermint Deployment

### PR DESCRIPTION
**Pull request by jeamick**
Addition of Ethermint Deployment

### CODE REVIEW

**Comment by adrianbrink** [comment]
Thank you very much. This looks very promising.

Could you remove everything that has currently a todo. For example the Docker section. Also, let's group the installation for Ethermint and Tendermint and make sure that they follow the same format.

Besides that it looks awesome.

**Comment by anoff** [comment]
Is there a possibility to run ethermint in a docker container similar to how we currently do it with `testrpc`?

**Comment by jeamick** [comment]
I think, before making the docker container, people should test it in order to know if there are some problems with the setup with Ethermint. And when we are sure that it is totally working we can do the docker container.

**Comment by iamtrask** [comment]
I agree with @jeamick

**Comment by axelhodler** [comment]
the dockerizing would be to make the setup easier for users such as they do not need to have a local go/ethermint/tendermint/geth install.

on a sidenote: could we opt for having the current default (docker / vanilla ethereum) and ethermint side by side? As it is now the ethermint docs overwrite the old docs.

**Comment by iamtrask** [comment]
@axelhodler I agree. I believe @jeamick and I also discussed this offline. In theory the main Readme should offer both as branches... perhaps in separate Markdown files.

**Comment by iamtrask** [comment]
That being said, I'm a big fan of the tutorial for building ethermint locally as it's not only useful for docker experts to be able to dockerize but also makes for a good fallback option.

**Comment by anoff** [comment]
Especially if you want to roll something out to several people it makes sense to do so via docker. A non docker solution is prone to 'works on my machine' problems and it will not integrate with the current setup as this is purely docker based.

**Comment by jeamick** [comment]
Yes @anoff  you're right! I will try to make a video demo for this repo.
If someone can do the docker file because I'm not an expert on it.

So to make things clear, let's make to differents repo right?

**Comment by jeamick** [comment]
how can I call it ?

**Comment by iamtrask** [comment]
given the other PR, i'll go ahead and close this one :) Great job!

**Comment by adrianbrink** [comment]
@iamtrask Could you reference the other PR here.

**Pull request closed without merging**
