### PR TITLE
Add version numbers to requirements.txt

### PR DESCRIPTION
**Pull request by davidrhodus**
https://github.com/OpenMined/PySonar/issues/39

### CODE REVIEW

**Comment by swaroopch** [comment]
@davidrhodus Can we use https://github.com/jazzband/pip-tools/ to generate the version numbers, so that it is easy to upgrade versions in future?

**Comment by davidrhodus** [comment]
@swaroopch I updated the commit using the pip-compile tool. Thanks for the tip!

**Comment by swaroopch** [comment]
@davidrhodus can you please include the source file (requirements.in) & commands so that this is upgradable

**Comment by iamtrask** [comment]
FYI - also being worked on here https://github.com/OpenMined/PySonar/pull/52

**Comment by davidrhodus** [comment]
@swaroopch pull request updated with (requirements.in) & commands added to the Readme. Please review and let know your thoughts

**Comment by swaroopch** [comment]
@davidrhodus LGTM!

**Review by iamtrask — APPROVED** [review]

**Pull request merged**
