### PR TITLE
:scissors: refactor: remove demo contracts

### PR DESCRIPTION
**Pull request by anoff**
Well...cleanup 🚿

### CODE REVIEW

**Comment by axelhodler** [comment]
@anoff the contracts are still referenced in the `migrations` folder

**Comment by anoff** [comment]
Not even sure what those scripts even do but removed the dead ref :)

**Comment by axelhodler** [comment]
> Not even sure what those scripts even do [...]

they are just some ordered scripts e.g.
```js
// migrations/1_hi_im.js
module.exports = function(deployer) {
  console.log('Hi i`m')
}
```

```js
// migrations/2_axel.js
module.exports = function(deployer) {
  console.log('axel')
}
```
`./node_modules/.bin/truffle migrate`

```bash
Running migration: 1_hi_im.js
Hi i`m
Saving artifacts...
Running migration: 2_axel.js
axel
Saving artifacts...
```

and TIL `migrate` wont run if there are not at least two migration files. Interesting. Will have a look into what truffle does exactly

**Comment by anoff** [comment]
Also turns out you need the `Migration.sol` for things to work.. I should really try to understand what things do before I delete them lol

**Comment by iamtrask** [comment]
Yessir @anoff! The migrations stuff helps automate things like smart contract lifecycle.

**Pull request merged**
